### ISSUE TITLE
Seu código não roda.

### ISSUE THREAD

**Issue by gorsqi** [tiagoluizrs/livro_flask#1]
`python run.py            
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import create_app
  File "/Users/work/Projetos/livro_flask/app.py", line 13, in <module>
    from controller.User import UserController
  File "/Users/work/Projetos/livro_flask/controller/User.py", line 1, in <module>
    from model.User import User
  File "/Users/work/Projetos/livro_flask/model/User.py", line 9, in <module>
    from model.Role import Role
  File "/Users/work/Projetos/livro_flask/model/Role.py", line 5, in <module>
    config = app_config[app_active]
KeyError: None`

### Tento rodar seu código e da esse erro. 

Estou estudando e o código que estou seguindo pelo livro da o mesmo erro.

Em que canal posso lhe solicitar ajuda?

**Comment by gorsqi** [comment]
Resolvido

**Comment by tiagoluizrs** [comment]
Olá. Você precisa estar a variável de ambiente. No Linux e Mac seria export FLASK_ENV=development, no windows set FLASK_ENV=development. Assim o app_active não será Nona.
